import assert from 'node:assert/strict';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { isTransientProviderFailure, retryAfterMs, transientRetryDelayMs, shouldRetryTransient, buildTransientFailureMessage } from '../runtime/provider-resilience.mjs';
assert.equal(isTransientProviderFailure({ status: 429 }), true);
assert.equal(isTransientProviderFailure({ status: 503 }), true);
assert.equal(retryAfterMs({ 'retry-after': '2' }), 2000);
assert.equal(transientRetryDelayMs(0, {}, { baseMs: 800, maxMs: 8000, jitter: 0 }), 800);
assert.equal(transientRetryDelayMs(2, {}, { baseMs: 800, maxMs: 8000, jitter: 0 }), 3200);
assert.equal(shouldRetryTransient({ status: 429, attempt: 0, maxRetries: 8 }), true);
assert.equal(shouldRetryTransient({ status: 429, attempt: 8, maxRetries: 8 }), false);
assert.equal(shouldRetryTransient({ status: 429, attempt: 0, maxRetries: 8, committed: true }), false);
assert.match(buildTransientFailureMessage({ provider: 'OpenRouter', model: 'z-ai/glm-5.2:free', status: 429, attempts: 9 }), /temporarily unavailable/);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = fs.readFileSync(path.join(root, 'scripts', 'lazydev.mjs'), 'utf8');
assert.match(src, /allow_fallbacks: true/);
assert.match(src, /PROVIDER_TRANSIENT_MAX_RETRIES[\s\S]*\|\| 8/);
console.log('provider resilience smoke: PASS');
