import assert from 'node:assert/strict';
import { isTransientProviderFailure, retryAfterMs, transientRetryDelayMs, shouldRetryTransient, buildTransientFailureMessage } from '../runtime/provider-resilience.mjs';
assert.equal(isTransientProviderFailure({ status: 503 }), true);
assert.equal(isTransientProviderFailure({ status: 529, body: 'service temporarily overloaded' }), true);
assert.equal(isTransientProviderFailure({ status: 400, body: 'invalid request' }), false);
assert.equal(retryAfterMs({ 'retry-after': '2' }), 2000);
assert.equal(transientRetryDelayMs(0, {}, { baseMs: 800, maxMs: 8000, jitter: 0 }), 800);
assert.equal(transientRetryDelayMs(2, {}, { baseMs: 800, maxMs: 8000, jitter: 0 }), 3200);
assert.equal(shouldRetryTransient({ status: 503, attempt: 0, maxRetries: 2 }), true);
assert.equal(shouldRetryTransient({ status: 503, attempt: 2, maxRetries: 2 }), false);
assert.equal(shouldRetryTransient({ status: 503, attempt: 0, maxRetries: 2, committed: true }), false);
assert.match(buildTransientFailureMessage({ provider: 'Gemini', model: 'flash', status: 503, attempts: 3 }), /temporarily unavailable/);
console.log('provider resilience smoke: PASS');
